# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - build
  - test
  - validation
  - package

#sast:
# stage: test
#include:
#- template: Security/SAST.gitlab-ci.yml


build-job:
  stage: build
  script:
    - cd restaurant
    - mvn clean compile

test-job:
  stage: test
  script:
    - cd restaurant
    - mvn test -Dgroups=\!ConnectionNeeded

checkstyle-job:
  stage: validation
  script:
    - cd restaurant
    - mvn checkstyle:check

package-job:
  stage: package
  script:
    - cd restaurant
    - mvn package
  artifacts:
    when: on_success
    expire_in: 30 days
    paths:
      - "restaurant/target/*.jar"